### ISSUE TITLE
[3.x] Zip folder downloaded from this installer contains a `composer.lock`

### ISSUE THREAD

**Issue by nunomaduro** [laravel/installer#105]
- Installer Version: latest

### Description:

The zip folder downloaded from this installer contains a `composer.lock` created from the machine where the zip file was originally created.

The problem is: when perform a `laravel new app`, the exact dependencies of that `composer.lock` file may *not* match a PHP version of the target machine.

### Steps To Reproduce:

Perform a `laravel new app` on a machine with php `v7.2.5`, and you will get this:

![EJ7R7d5WoAE6eXx](https://user-images.githubusercontent.com/5457236/69714236-5d3d5d00-1106-11ea-9ead-95c713566852.jpeg)

### Solution

Remove the `composer.lock` from those zip files to mimicate the bahavior of the normal `composer create-project` command.

**Comment by driesvints** [comment]
Can you please give the version of the installer you're testing this with? We did a new major release this week. Is this on 3.0?

**Comment by driesvints** [comment]
@nunomaduro also: we can't remove the `composer.lock` file since that would remove the entire purpose of the installer. It would slow down the process tremendously.

**Comment by taylorotwell** [comment]
Can't remove the `composer.lock` as it defeats the entire purpose of having a super fast installer. Upgrade your PHP or use composer create-project if you must remain on a lower PHP version. 👍

**Comment by driesvints** [comment]
I've pushed a commit that sets the minimum PHP version to 7.2.9 as well.
