### ISSUE TITLE
Create new project failing on PHP 7.2

### ISSUE THREAD

**Issue by JeremyRoundill** [laravel/installer#117]
- Installer Version: 3.0.1

### Description:

Running `laravel new blog` on PHP 7.2 results in error

    Problem 1
        - Installation request for mockery/mockery 1.4.0 -> satisfiable by mockery/mockery[1.4.0].
        - mockery/mockery 1.4.0 requires php ^7.3.0 -> your PHP version (7.2.23) does not satisfy that requirement.

See: https://stackoverflow.com/questions/61900738/laravel-new-blog-not-work-mockery-mockery-1-4-0/61900857

### Steps To Reproduce:

Run `laravel new blog` on PHP 7.2

### Solution:

Looks like the files on cabinet.laravel.com have correct composer.json files (i.e. they contain `"mockery/mockery": "^1.3.1"`), however they must have been prepared in an environment with a higher PHP version, because the composer.lock files list a version 1.4 mockery, which requires PHP 7.3 or higher.

Either change line 66 of NewCommand.php to be `update` instead of `install`, or fix the files on cabinet.laravel.com

**Comment by GrahamCampbell** [comment]
> Either change line 66 of NewCommand.php to be update instead of install

That would be a bad idea, and would defeat the whole point of shipping a composer.lock.

**Comment by GrahamCampbell** [comment]
> however they must have been prepared in an environment with a higher PHP version

Yeh, this is the bug.

**Comment by driesvints** [comment]
We've decided to throw an exception warning on 7.3 and direct people to `composer create-project instead`.
