### ISSUE TITLE
Laravel installer clears setgid bit on storage and bootstrap/cache

### ISSUE THREAD

**Issue by marveloo** [laravel/installer#122]
- Installer Version: 3.2.0

### Description:

When creating new files, `setgid` bit (and consequentially the owning group) should be inherited from parent directories. However Laravel Installer explicitly sets `755` as permission attributes to `storage` and `bootstrap/cache` directories as well as all the directories and files inside. As a result `setgid` bit and therefore the owning group for files which are created later get lost.

### Steps To Reproduce:

```
mkdir www
chgrp www-data www
chmod g+s www  # setting `setgid` bit on `www` directory

cd www
laravel new myproject
```

Now, let's have a look at the contents of `my project`:

```
$ cd myproject
$ ll
total 772
drwxr-sr-x 12 marveloo www-data   4096 Jul  9 23:44 ./
drwxr-sr-x  3 marveloo www-data   4096 Jul  9 23:44 ../
-rw-r--r--  1 marveloo www-data    220 Jul  9 23:44 .editorconfig
-rw-r--r--  1 marveloo www-data    829 Jul  9 23:44 .env
-rw-r--r--  1 marveloo www-data    778 Jul  9 23:44 .env.example
-rw-r--r--  1 marveloo www-data    111 Jul  9 23:44 .gitattributes
-rw-r--r--  1 marveloo www-data    163 Jul  9 23:44 .gitignore
-rw-r--r--  1 marveloo www-data    174 Jul  9 23:44 .styleci.yml
-rw-r--r--  1 marveloo www-data   4594 Jul  9 23:44 README.md
drwxr-sr-x  6 marveloo www-data   4096 Jul  9 23:44 app/
-rw-r--r--  1 marveloo www-data   1686 Jul  9 23:44 artisan
drwxr-sr-x  3 marveloo www-data   4096 Jul  9 23:44 bootstrap/
-rw-r--r--  1 marveloo www-data   1586 Jul  9 23:44 composer.json
-rw-r--r--  1 marveloo www-data 227978 Jul  9 23:44 composer.lock
drwxr-sr-x  2 marveloo www-data   4096 Jul  9 23:44 config/
drwxr-sr-x  5 marveloo www-data   4096 Jul  9 23:44 database/
-rw-r--r--  1 marveloo www-data 453407 Jul  9 23:44 package-lock.json
-rw-r--r--  1 marveloo www-data   1034 Jul  9 23:44 package.json
-rw-r--r--  1 marveloo www-data   1215 Jul  9 23:44 phpunit.xml
drwxr-sr-x  2 marveloo www-data   4096 Jul  9 23:44 public/
drwxr-sr-x  6 marveloo www-data   4096 Jul  9 23:44 resources/
drwxr-sr-x  2 marveloo www-data   4096 Jul  9 23:44 routes/
-rw-r--r--  1 marveloo www-data    563 Jul  9 23:44 server.php
drwxr-xr-x  5 marveloo www-data   4096 Jul  9 23:44 storage/
drwxr-sr-x  4 marveloo www-data   4096 Jul  9 23:44 tests/
drwxr-sr-x 44 marveloo www-data   4096 Jul  9 23:44 vendor/
-rw-r--r--  1 marveloo www-data    538 Jul  9 23:44 webpack.mix.js
```

As we can see, all the files and folders were assigned to group `www-data` as expected and the `setgid` bit was set on all the folders as well... except for `storage`.

And here we have the contents of `storage` and `bootstrap/cache`:

```
$ ll bootstrap/cache storage
bootstrap/cache:
total 32
drwxr-xr-x 2 marveloo www-data  4096 Jul  9 23:44 ./
drwxr-sr-x 3 marveloo www-data  4096 Jul  9 23:44 ../
-rwxr-xr-x 1 marveloo www-data    14 Jul  9 23:44 .gitignore*
-rwxr-xr-x 1 marveloo marveloo   938 Jul  9 23:44 packages.php*
-rwxr-xr-x 1 marveloo marveloo 13766 Jul  9 23:44 services.php*

storage:
total 20
drwxr-xr-x  5 marveloo www-data 4096 Jul  9 23:44 ./
drwxr-sr-x 12 marveloo www-data 4096 Jul  9 23:44 ../
drwxr-xr-x  3 marveloo www-data 4096 Jul  9 23:44 app/
drwxr-xr-x  6 marveloo www-data 4096 Jul  9 23:44 framework/
drwxr-xr-x  2 marveloo www-data 4096 Jul  9 23:44 logs/
```

So we can see that none of the folders got `setgid` bit. And in turn `packages.php` and `services.php` were unable to inherit `www-data` group because these files were created after `755` was applied to their parents where `setgid` got lost.

### Possible Solutions:

1. Apply `w` bit to files and folders which require this but leave all other permission bits untouched;
2. Apply `755` but leave all special permission bits (i.e. `setuid`, `setgid` and `sticky` bits) untouched;
3. Don't apply anything and get rid of [`prepareWritableDirectories`](https://github.com/laravel/installer/blob/cea8542d73684fe30a0752e50406ccb99819505c/src/NewCommand.php#L64) method call completely (this is my preferred solution, read below).

Currently `prepareWritableDirectories` explicitly sets `755` permissions to all the files that need to be writable by the server, however the user who is able to run `laravel install myproject` must have the user part of `umask` set to `0`, otherwise the installer won't run at all. Which means that the `storage` and `bootstrap/cache` directories will always be created as writable anyway regardless of all the "job" done by  `prepareWritableDirectories`.

**Comment by driesvints** [comment]
We probably aren't going to make changes here since it's been going fine for years already. Feel free to adjust permissions after installing.

**Comment by marveloo** [comment]
I think I failed to explain the issue thoroughly and how easy it is to fix it, so in case you guys decide to change your mind sometime, here are another two cents of mine:

The fix only requires deleting [one line of code](https://github.com/laravel/installer/blob/cea8542d73684fe30a0752e50406ccb99819505c/src/NewCommand.php#L64) and that would be all.

Explanation:

To put it simply, without giving `write` permissions to each and every directory Laravel Installer wouldn't be able to put new files there which means that in order for installer to be able to install new project it needs to create writable directories throughout the whole project. So there is no need to `prepareWritableDirectories()` by setting `755` to any specific directory or file because the whole project is already writable. This method is redundant and furthermore it creates some additional minor issues but solves absolutely nothing.
