### ISSUE TITLE
Can't install on PHP 7.4

### ISSUE THREAD

**Issue by MarceauKa** [laravel/installer#127]
- Installer Version: 4.0.0

### Description:

Can't install when running PHP 7.4.

### Steps To Reproduce:

<img width="1035" alt="screenshot" src="https://user-images.githubusercontent.com/1665333/92138547-ccbb4800-ee0e-11ea-96ec-574007f15c55.png">

**Comment by driesvints** [comment]
Seems to be a problem with a globally installed package. The installer doesn't uses php cs fixer.
