### ISSUE TITLE
Remove command blocks Laravel Installer on Windows PowerShell

### ISSUE THREAD

**Issue by volkanmetin** [laravel/installer#128]
- Installer Version: 4.0.0

### Description:

When I tried to create a new Laravel project via installer, "rm" method was not recognized and process stopped. Remove command is not working on Windows PowerShell.

Remove command: https://github.com/laravel/installer/pull/124/files#diff-2f97ce541989fd5777bb883c213d1805R61

### Steps To Reproduce:

Run `laravel new blog`

![image](https://user-images.githubusercontent.com/1078613/92173392-ab754e80-ee44-11ea-86b6-feec2bead285.png)

**Comment by tyler36** [comment]
Same issue here.

Lavavel Install: 4.0.0
OS: Win10
Shell: Tried from Powershell, Powershell Core 7.0.3, CMD

**Comment by ExpDev07** [comment]
Getting the same error.

Lavavel Install: 4.0.0
OS: Win10
Shell: Tried both `cmd.exe` and Powershell.

**Comment by ExpDev07** [comment]
I believe this is the line that is causing the issue: https://github.com/laravel/installer/blob/master/src/NewCommand.php#L94.

**Comment by tyler36** [comment]
Confirmed.
Laravel Installer ```4.0.1``` resolves the problem for me.

Thank you.
