### ISSUE TITLE
Windows: 'rm' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by pschilly** [laravel/installer#141]
When attempting to create a new project on Windows - the Installer throws the following error:

`'rm' is not recognized as an internal or external command,
operable program or batch file.`

Reproducable with the following command: 
`laravel new jetstream --dev --jet`

This is noted in Powershell as well as the regular CMD line. A tennative fix for this is using Git BASH.

Potential perm fix for Windows is to use the command "del" instead of "rm" as "rm" is not a native Windows command line command.

**Comment by dleicam** [comment]
@pschilly, you already have an fresh version with the latest changes.

If so, try running a "composer global dump-autoload".

In principle, this problem is already overcome.

**Comment by vincentkosciuszko** [comment]
The 4.0 version doesn't work on Windows, you have to install the dev-master version.

**Comment by magamine** [comment]
Hello 
I'm facing the same problem and already did execute 
`composer global dump-autoload`
The same error is reproducable with the following command:
`laravel new test`

**Comment by vincentkosciuszko** [comment]
@magamine use `composer global require laravel/installer:dev-master`.

**Comment by Braunson** [comment]
@vincentkosciuszko Tried that also (Win-10) 

Error returned is `The system cannot find the file specified`.

**Comment by Bradez** [comment]
Run `composer global require laravel/installer` again (now that v4.0.1 has been released) and it'll work. 👍

**Comment by swaghacker** [comment]
facing issue after change rm-rf into rmdir 
                                   The system cannot find the file specified.

**Comment by sivadasrajan** [comment]
For me it happened because of I reinstalled WAMP.
so I tried these in sequence and it worked.
(I use Laravel v8.5.9 on windows with wamp server's php)
1) Reinstalled composer from setup
2) "composer global remove laravel/installer"
3) "composer global require laravel/installer"

**Comment by iotronlab** [comment]
Refer to this video, @statstical-anomaly thanks. It worked perfectly.
https://youtu.be/wht2hEomRhg

**Comment by helloasir** [comment]
> @magamine use `composer global require laravel/installer:dev-master`.

its works for me . thanks

**Comment by dianasmara** [comment]
.

**Comment by Shorlex** [comment]
_`composer global require laravel/installer`_  Just worked for me.
