### ISSUE TITLE
Installer crashes with combination of --jet and -n

### ISSUE THREAD

**Issue by snapey** [laravel/installer#144]
- Installer Version: 4.0.1

### Description:
When using non-interactive mode, the installer crashes

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Laravel\Installer\Console\NewCommand::installJetstream() must be of the type string, null given, called in /Users/mark/.composer/vendor/laravel/installer/src/NewCommand.php on line 116 and defined in /Users/mark/.composer/vendor/laravel/installer/src/NewCommand.php:135

### Steps To Reproduce:

`laravel new myproject --dev --jet -n`

Installer requires decisions about jetstream (livewire/inertia, teams) but there does not seem to be a way to provide these answers when non-interactive

**Comment by driesvints** [comment]
Thanks. I sent in a PR for that: https://github.com/laravel/installer/pull/146

**Comment by driesvints** [comment]
Fixed.

**Comment by bsienn** [comment]
I still have this issue

windows 10
php 7.3

#148

**Comment by dimawebmaker** [comment]
Had same error. 
Reinstall laravel installer helps me.
`
composer global remove laravel/installer

composer global require laravel/installer
`

[source](https://stackoverflow.com/questions/61051679/how-to-update-laravel-installer-laravel-installer-to-latest-version)

**Comment by bsienn** [comment]
@dimawebmaker yes, your provided solution worked. Many thanks for your time.
