### ISSUE TITLE
[Feature request] Check server requirements before creating any files and directories

### ISSUE THREAD

**Issue by SharakPL** [laravel/installer#151]
When I create new app with `laravel new myapp` I get an error:
> Your requirements could not be resolved to an installable set of packages.
> 
>  Problem 1
>    - phpunit/phpunit 9.4.x-dev requires ext-dom * -> the requested PHP extension dom is missing from your system.
> ...

I know this is a one time issue and goes away with installing missing php extensions, but would it be possible to do this checking __before__ creating any app folders including /myapp?

**Comment by driesvints** [comment]
@SharakPL feel free to PR if you want

**Comment by SharakPL** [comment]
@driesvints can you tell me which script/package in Laravel is responsible for checking requirements?

**Comment by driesvints** [comment]
It'll need to be done inside the installer somewhere. Probably where composer is run.

**Comment by SharakPL** [comment]
I know, but which script does the checking in current state? Is it in laravel somewhere  (I assume it is as it downloads laravel package before checking requiements) or maybe composer does that iautomatically or is it already in laravel/installer (just not in the right order)?
