### ISSUE TITLE
Installation fails when using --quiet

### ISSUE THREAD

**Issue by jonsugar** [laravel/installer#154]
- Installer Version: 4.0.4

### Description:
When using `--quiet` basic installation is successful (the new Laravel project is created) but setting artisan to executable fails. This results in APP_URL and DB_DATABASE not being configured in .env as well as Jetstream UI failing to install.

I think this is due to chmod interpreting --quiet as a directory since its not a flag that it accepts.

### Steps To Reproduce:
run `laravel new <name> --quiet`.

**Comment by driesvints** [comment]
I can indeed reproduce this. Will look into it. Appreciating help in the meantime.

**Comment by driesvints** [comment]
I sent in a PR for it.
