### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Symfony\Component\Console\Question\ConfirmationQuestion

### ISSUE THREAD

**Issue by gasner** [laravel/installer#157]
- Installer Version: 4.0.4

### Description:
I try to install a new project with --jet.
And I get  this:

Fatal error: Uncaught Error: Class 'Symfony\Component\Console\Question\ConfirmationQuestion' not found in C:\Users\××œ×¢×“\AppData\Roaming\Composer\vendor\symfony\console\Style\SymfonyStyle.php on line 283

Error: Class 'Symfony\Component\Console\Question\ConfirmationQuestion' not found in C:\Users\××œ×¢×“\AppData\Roaming\Composer\vendor\symfony\console\Style\SymfonyStyle.php on line 283

Call Stack:
    0.0004     399672   1. {main}() C:\Users\××œ×¢×“\AppData\Roaming\Composer\vendor\laravel\installer\bin\laravel:0
    0.0139    1283904   2. Symfony\Component\Console\Application->run() C:\Users\××œ×¢×“\AppData\Roaming\Composer\vendor\laravel\installer\bin\laravel:13
    0.0520    1547136   3. Symfony\Component\Console\Application->doRun() C:\Users\××œ×¢×“\AppData\Roaming\Composer\vendor\symfony\console\Application.php:140
    0.0537    1624912   4. Symfony\Component\Console\Application->doRunCommand() C:\Users\××œ×¢×“\AppData\Roaming\Composer\vendor\symfony\console\Application.php:264
    0.0537    1624912   5. Laravel\Installer\Console\NewCommand->run() C:\Users\××œ×¢×“\AppData\Roaming\Composer\vendor\symfony\console\Application.php:916
    0.0541    1626720   6. Laravel\Installer\Console\NewCommand->execute() C:\Users\××œ×¢×“\AppData\Roaming\Composer\vendor\symfony\console\Command\Command.php:258
    2.4053    1873016   7. Symfony\Component\Console\Style\SymfonyStyle->confirm() C:\Users\××œ×¢×“\AppData\Roaming\Composer\vendor\laravel\installer\src\NewCommand.php:55

Variables in local scope (#7):
  $default = FALSE
  $question = 'Will your application use teams?'

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
