### ISSUE TITLE
JetStream and Teams not getting installed when passed as arguments

### ISSUE THREAD

**Issue by TAINCER** [laravel/installer#159]
- Installer Version: 4.0.5

### Description:
when running `laravel new ProjectName --jet` or `laravel new ProjectName --jet --teams` the installer just installs a normal laravel 8 project.
The JetStream Asci art appears with the Stack question, but that's everything you see in terms of jetstream.

### Steps To Reproduce:
run `laravel new ProjectName --jet` or `laravel new ProjectName --jet` on Windows 10 (2004).

**Comment by driesvints** [comment]
Working fine for me. If there's anything specific you want to fix feel free to send in a PR.
