### ISSUE TITLE
'rm' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by egyleader** [laravel/installer#160]
- Installer Version: 4.0.0

### Description:
when installing laravel jetstream project from power-shell in windows 10 it gives me this error :

`'rm' is not recognized as an internal or external command, operable program or batch file.

it works as expected when using git bash though 
`

### Steps To Reproduce:

1. open power-shell on windows 10 

2. type : ` laravel new project --jet `

3. select inertia as your stack 

4. the error will appear weather you choose teams feature or not ..

**Comment by driesvints** [comment]
We're not using Windows specifically ourselves but are appreciating PRs to help resolve this.

**Comment by taylorotwell** [comment]
No plans to take any action on this internally.
