### ISSUE TITLE
Installer claiming application already exists on an empty directory

### ISSUE THREAD

**Issue by lupinitylabs** [laravel/installer#161]
- Installer Version: 4.0.5

### Description:

If `laravel new` is executed on an empty directory, I would expect the installer to build a new empty Laravel 8 project in the current directory. Instead, it throws an **Application already exists** `RuntimeException`.

Looking at the code, the installer script already checks if the `$directory` is the current working directory, but it fails because `$directory` is not resolved into an absolute path and thus contains "." at the time of execution.

```php
if ((is_dir($directory) || is_file($directory)) && $directory != getcwd())
```

### Steps To Reproduce:

```bash
mkdir ~/test && cd ~/test
laravel new
```

**Comment by driesvints** [comment]
We don't support running the command in an existing dir.

**Comment by lupinitylabs** [comment]
That's unfortunate. I thought it did work in previous versions of the installer? 
Also, calling the installer without the name parameter should not be possible at all then, right?
