### ISSUE TITLE
Says "Application already exists!" inside empty directory. Prevents install.

### ISSUE THREAD

**Issue by Zenahr** [laravel/installer#166]
- Installer Version: 4.0.5

### Description:
Running `laravel new . --jet` inside an empty directory fails. There are also no hidden files left over. Might be related to #165. (residue?)

![image](https://user-images.githubusercontent.com/47085752/96356888-f3022200-10f4-11eb-889d-5543d248bd2e.png)

### Steps To Reproduce:

1. Run `laravel new . --jet`
2. Delete files and folders
3. Run `laravel new . --jet` again
4. Observe bug

**Comment by driesvints** [comment]
The installer doesn't supports empty directories.

**Comment by brucebrophy** [comment]
Hey @driesvints, didn't the previous versions of the installer support installations into empty directories?

**Comment by driesvints** [comment]
Not officially.

**Comment by Zenahr** [comment]
Well before closing it it would be cool to at least suggest a change. For example display an error message that hints to the user that an empty directory might cause the problem. I was confused and had no pointers to resolve the issue when it had happened.

**Comment by driesvints** [comment]
@Zenahr if you want you can send in a pr 👍
