### ISSUE TITLE
Error to execute laravel new

### ISSUE THREAD

**Issue by mccarlosen** [laravel/installer#171]
- Installer Version: 3.0.1

### Description:
I execute `laravel new lara-8` and get this error within homestead

### Steps To Reproduce:

![image](https://user-images.githubusercontent.com/8524361/98148549-f2aaaa80-1e9a-11eb-93ee-e1bce7f2d86e.png)

**Comment by driesvints** [comment]
Please upgrade to the latest Laravel installer version.
