### ISSUE TITLE
[4.1.0]  Class Inertia\Inertia not found

### ISSUE THREAD

**Issue by Simoneu01** [laravel/installer#173]
- Installer Version: 4.1.0

### Description:
"Class Intertia\Inertia not found"
![image](https://user-images.githubusercontent.com/43807696/98393510-a9548980-2059-11eb-941d-27c64fad3f7f.png)
Flare: https://flareapp.io/share/xPQpJ0km

### Steps To Reproduce:
1. Install Laravel Installer
2. Create new project with "laravel new --jett project"
3. Both choice "Livewire" and "Inertia" don't work
4. php artisan serve

**Comment by driesvints** [comment]
Can't reproduce with the above steps.

**Comment by Simoneu01** [comment]
@driesvints i'm on windows machine, maybe this can create a problem?

**Comment by driesvints** [comment]
If you're on a Windows machine I can't really help you out sorry. Do you have the `fileinfo` extension installed? That turned out to be a culprit in the past. You might also want to upgrade to composer 2. If you find a specific bug with windows feel free to PR a fix if you can.

**Comment by Simoneu01** [comment]
found the error, if the folder has spaces it doesn't work
