### ISSUE TITLE
Cannot create project (chdir(): No such file or directory (errno 2))

### ISSUE THREAD

**Issue by DrOreo002** [laravel/installer#174]
- Installer Version: 4.1.0

### Description:
Whenever I run `laravel new <project_name>` command it throw that error. I'm also running on composer version 2 (2.0.5). I also saw that it want to create a project in this path `Created project in I:\Programming Project\Laravel/blog` is it supposed to be `Created project in I:\Programming Project\Laravel\blog` instead?

### Steps To Reproduce:
Run `laravel new <project_name>`

**Comment by GrahamCampbell** [comment]
This is fixed in composer 2.0.6.

**Comment by driesvints** [comment]
@DrOreo002 can you try in composer v2?

**Comment by DrOreo002** [comment]
Yep composer 2.0.6 seems to fix it, thank you.
