### ISSUE TITLE
Install in current directory

### ISSUE THREAD

**Issue by hsleewis** [laravel/installer#180]
In some scenario's it's useful to create a new project in the current directory.
I know the installer doesn't allow "." as directory name, but is there a special reason why? 

I commented out this part of installer/src/NewCommand.php and it works perfectly fine.
```
if (! $input->getOption('force')) {
  $this->verifyApplicationDoesntExist($directory);
}

if ($input->getOption('force') && $directory === '.') {
  throw new RuntimeException('Cannot use --force option when using current directory for installation!');
}
```

**Comment by driesvints** [comment]
Because we consider it dangerous as it could overwrite existing files.

**Comment by hsleewis** [comment]
Thanks for the fast reply @driesvints!

Making it a separate option with a very explicit warning that needs a confirmation, would that make it acceptable?

**Comment by driesvints** [comment]
No, we're not changing this sorry.
