### ISSUE TITLE
Add PHP 8 Support

### ISSUE THREAD

**Issue by C0kkie** [laravel/installer#181]
If i want to install the installer i get

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - illuminate/support v6.18.41 requires php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.
    - laravel/envoy v1.6.5 requires illuminate/support ~4.1 || ~5.0 || ^6.0 -> satisfiable by illuminate/support[v6.18.41].
    - laravel/envoy is locked to version v1.6.5 and an update of this package was not requested.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by GrahamCampbell** [comment]
The recommended way to install Laravel is `composer create-project`, rather than this installer, as of Composer 2.0.0's release (I think??? // cc @driesvints).

**Comment by driesvints** [comment]
The installer only works with the latest Laravel version and not Laravel 6.

**Comment by C0kkie** [comment]
Who is talking about laravel 6?

**Comment by driesvints** [comment]
You are:

> - illuminate/support v6.18.41

**Comment by C0kkie** [comment]
C:\Users\Florian>composer global require laravel/installer
Changed current directory to C:/Users/Florian/AppData/Roaming/Composer
Using version ^4.1 for laravel/installer
./composer.json has been updated
Running composer update laravel/installer
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - illuminate/support v6.18.41 requires php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.
    - laravel/envoy v1.6.5 requires illuminate/support ~4.1 || ~5.0 || ^6.0 -> satisfiable by illuminate/support[v6.18.41].
    - laravel/envoy is locked to version v1.6.5 and an update of this package was not requested.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by driesvints** [comment]
You're trying to require the laravel installer globally without updating the underlying dependencies that other global packages have already set. 

Try: `composer global require laravel/installer -W`

**Comment by mdmuzaffer** [comment]
Update your composer.json file with my below code and then add your added package under "require": { } object, It will work
don't forget run command update composer


{
"name": "laravel/laravel",
"type": "project",
"description": "The Laravel Framework.",
"keywords": ["framework", "laravel"],
"license": "MIT",
"require": {
		"php": "^7.3|^8.0",
		"fideloper/proxy": "^4.4",
		"fruitcake/laravel-cors": "^2.0",
		"guzzlehttp/guzzle": "^7.0.1",
		"laravel/framework": "^8.40",
		"laravel/socialite": "^5.3",
		"laravel/tinker": "^2.5",
		"dompdf/dompdf": "^1.0",
		"intervention/image": "^2.5",
		"maatwebsite/excel": "^3.1",
		"softon/indipay": "^1.2"
	},
"require-dev": {
"facade/ignition": "^2.5",
"fakerphp/faker": "^1.9.1",
"laravel/sail": "^1.0.1",
"laravel/ui": "^3.3",
"mockery/mockery": "^1.4.2",
"nunomaduro/collision": "^5.0",
"phpunit/phpunit": "^9.3.3"
},
"autoload": {
	"psr-4": {
		"App\\": "app/"
	},
	"classmap": [
		"database/seeds",
		"database/factories"
	],
	 "files": [
	"app/helper/helpers.php"
	]
},
"autoload-dev": {
	"psr-4": {
		"Tests\\": "tests/"
	}
},

"scripts": {
	"post-autoload-dump": [
		"Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
		"@php artisan package:discover --ansi"
	],
	"post-root-package-install": [
		"@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
	],
	"post-create-project-cmd": [
		"@php artisan key:generate --ansi"
	]
},

"extra": {
"laravel": {
"dont-discover": []
}
},
"config": {
"optimize-autoloader": true,
"preferred-install": "dist",
"sort-packages": true
},
"minimum-stability": "dev",
"prefer-stable": true
}
