### ISSUE TITLE
`The "no-ansi" option does not exist` exception after upgrading

### ISSUE THREAD

**Issue by martylamoureux** [laravel/installer#182]
- Installer Version: 4.1.1

### Description:
After upgrading my Mac to PHP 8.0.1 (After linking PHP 7.4, I still have the issue by the way), Composer 2.0.8 and Laravel Installer to the latest version, I cannot run the `laravel new` command anymore.

I got a `The "no-ansi" option does not exist"`.

Here is the full output with verbose enabled : 

```
_                               _
| |                             | |
| |     __ _ _ __ __ ___   _____| |
| |    / _` | '__/ _` \ \ / / _ \ |
| |___| (_| | | | (_| |\ V /  __/ |
|______\__,_|_|  \__,_| \_/ \___|_|


In Input.php line 150:

  [Symfony\Component\Console\Exception\InvalidArgumentException]
  The "no-ansi" option does not exist.


Exception trace:
  at /Users/martylamoureux/.composer/vendor/symfony/console/Input/Input.php:150
 Symfony\Component\Console\Input\Input->getOption() at /Users/martylamoureux/.composer/vendor/laravel/installer/src/NewCommand.php:239
 Laravel\Installer\Console\NewCommand->runCommands() at /Users/martylamoureux/.composer/vendor/laravel/installer/src/NewCommand.php:103
 Laravel\Installer\Console\NewCommand->execute() at /Users/martylamoureux/.composer/vendor/symfony/console/Command/Command.php:277
 Symfony\Component\Console\Command\Command->run() at /Users/martylamoureux/.composer/vendor/symfony/console/Application.php:974
 Symfony\Component\Console\Application->doRunCommand() at /Users/martylamoureux/.composer/vendor/symfony/console/Application.php:291
 Symfony\Component\Console\Application->doRun() at /Users/martylamoureux/.composer/vendor/symfony/console/Application.php:167
 Symfony\Component\Console\Application->run() at /Users/martylamoureux/.composer/vendor/laravel/installer/bin/laravel:13

new [--dev] [--jet] [--stack [STACK]] [--teams] [--prompt-jetstream] [-f|--force] [--] <name>
```

### Steps To Reproduce:

On my side : upgrade PHP, Composer and Laravel Updater, then the issue came up.

**Comment by driesvints** [comment]
Try running `composer global update`.

**Comment by jasonlfunk** [comment]
@driesvints This is happening to me on the latest versions:

```
➜  ~ composer --version
Composer version 2.0.11 2021-02-24 14:57:23
➜  ~ laravel --version
Laravel Installer 4.2.4
➜  ~ php --version
PHP 7.4.16 (cli) (built: Mar  4 2021 20:52:51) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies
    with blackfire v1.49.0~mac-x64-non_zts74, https://blackfire.io, by Blackfire
➜  ~ laravel new test                                                                                      

 _                               _
| |                             | |
| |     __ _ _ __ __ ___   _____| |
| |    / _` | '__/ _` \ \ / / _ \ |
| |___| (_| | | | (_| |\ V /  __/ |
|______\__,_|_|  \__,_| \_/ \___|_|


                                        
  The "no-ansi" option does not exist.  
                                        

new [--dev] [--git] [--branch BRANCH] [--github [GITHUB]] [--organization ORGANIZATION] [--jet] [--stack [STACK]] [--teams] [--prompt-jetstream] [-f|--force] [--] <name>
```

**Comment by driesvints** [comment]
Seems to work fine for me:

![Screenshot 2021-03-31 at 11 34 14](https://user-images.githubusercontent.com/594614/113123649-0d4c3a00-9215-11eb-9e9e-91ac10f3c040.jpg)

**Comment by jasonlfunk** [comment]
Okay, so what else could be the cause? As far as I know, all my packages are up to date.

**Comment by webworkerJoshua** [comment]
I have the same problem:
![laravel-bug-no-ansi](https://user-images.githubusercontent.com/44984072/114316438-e4c11b80-9b03-11eb-9b4f-a00b22fbd068.png)

Occured at a MacBook Pro 13" with Apple M1, PHP 7.4, Composer 2.0.12 and Laravel Installer 4.2.4

**Comment by webworkerJoshua** [comment]
Even after re-installing laravel and composer the error occurs.
Device: Macbook Pro 13" M1, MacOS 11.2.3
PHP: 7.4.14
Composer: 2.0.12
Laravel Installer: 4.2.4

Does anybody has an idea how to solve this?

```
❯ ~ php --version
PHP 7.4.14 (cli) (built: Jan  8 2021 01:35:35) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.14, Copyright (c), by Zend Technologies
❯ ~ composer -V
Composer version 2.0.12 2021-04-01 10:14:59
❯ ~ laravel --version
Laravel Installer 4.2.4
❯ ~ laravel new test

 _                               _
| |                             | |
| |     __ _ _ __ __ ___   _____| |
| |    / _` | '__/ _` \ \ / / _ \ |
| |___| (_| | | | (_| |\ V /  __/ |
|______\__,_|_|  \__,_| \_/ \___|_|



  The "no-ansi" option does not exist.


new [--dev] [--git] [--branch BRANCH] [--github [GITHUB]] [--organization ORGANIZATION] [--jet] [--stack [STACK]] [--teams] [--prompt-jetstream] [-f|--force] [--] <name>
```

**Comment by webworkerJoshua** [comment]
I found the bug in my case!
There was another global composer dependency which used symfony/console with '5.x-dev' as version.
After updating that dependency and another `composer global update` the laravel installer works againl

**Comment by jasonlfunk** [comment]
Yes, that turned out to be my problem too. The installer isn't compatible with symfony/console `5.x-dev` but will still happily accept it as a dependency.

**Comment by corcronje** [comment]
I also encountered this issue, with symfony/console:5.3.0. Downgrading to symfony/console:5.2.8 resolved the issue for me.

`composer global require symfony/console:5.2.x`

[[console] Negatable option are null by default](https://github.com/symfony/console/commit/17cbb9e9e631c20bd5fd9ba3f507e6de6adcf843)

**Comment by patobhen** [comment]
Hi

Follow this steps

1. composer create-project laravel/laravel name-project

2. cd name-project

Something is wrong with the package laravel installer and the global variables

Regards

**Comment by dlmcglone** [comment]
downgrading symfony also worked for me.

**Comment by ledunggit** [comment]
> I also encountered this issue, with symfony/console:5.3.0. Downgrading to symfony/console:5.2.8 resolved the issue for me.
> 
> `composer global require symfony/console:5.2.x`
> 
> I see that some changes related to the --no-ansi option is being made here, [[console] Negatable option are null by default](https://github.com/symfony/console/commit/17cbb9e9e631c20bd5fd9ba3f507e6de6adcf843)

I did the same thing as this guy and it worked perfect. Thanks very much to this guy.

**Comment by exeptionerror** [comment]
[[Solved] The “no-ansi” option does not exist in Laravel
](https://exerror.com/the-no-ansi-option-does-not-exist-in-laravel)

**Comment by artsocode** [comment]
Hi! **no-ansy** problem still exitst on Win10 WSL, php **8.0.7**, Laravel Installer **4.0.0**, Composer **2.1.3**, symfony/console: **5.2.x.**
For me works only: `composer create-project laravel/laravel <project-name>`
