### ISSUE TITLE
Feature Request : Revert back to parent folder after methods that use chdir, in cases where one overrides the execute method as it throws errors.  

### ISSUE THREAD

**Issue by patrickcurl** [laravel/installer#198]
I'm overriding this to create some additional modifications. 

One thing I've noticed is I have in my custom package that extends yours: 

```php
protected function execute(InputInterface $input, OutputInterface $output)
    {
        $executionCode = parent::execute($input, $output);
        if ($executionCode === 0) { 
			$this->replaceInFile('SESSION_DRIVER=file', 'SESSION_DRIVER=redis', $envFile);
		 // my custom code
		}
		return $executionCode;
    }
```

This works like a charm, except if I use --teams in jet. Basically it breaks directories which I use to setup some symlinks to automatically propagate nginx locally...as well as editing the .env file is now looking for it in myapp/myapp.env instead of myapp.env. 

The fix is basically reverting back to the parent directory before calling my code if using teams. Which seems a little hackety since --jet without teams works. I'm wondering if maybe you could just automatically chdir back whenever you go into a directory. It's a small thing but seems to be a little "safer" in terms of congruency. 

My easy fix was this though: 

```php 
class NewCommand extends BaseCommand
{
    protected $topDir;

	/**
     * Execute the command.
     *
     * @param  \Symfony\Component\Console\Input\InputInterface  $input
     * @param  \Symfony\Component\Console\Output\OutputInterface  $output
     * @return int
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->topDir = getcwd();
        $executionCode = parent::execute($input, $output);
        chdir($this->topDir);
        if ($executionCode === 0) {
			//my custom code
		}
		return $executionCode;
	}
```

I guess a proposed fix would be add the $topdir property, then right before returning from the execute method chdir back. Or do so in functions that shift the current working directory, in case someone might be overriding another method. 

It's just kind of a nit-pick since I've got it fixed/patched and should now just work, but others might get stuck, so it may help others. :)

**Comment by driesvints** [comment]
No plans for this sorry.
