### ISSUE TITLE
Allow to push the new repository on Gitlab

### ISSUE THREAD

**Issue by windu2b** [laravel/installer#204]
Like the `--github` option, it would be usefull to have an option `--gitlab`, with an optional value `--public`, allowing to push to Gitlab.
The `--organization` option can be used at the same time.

For example:
`laravel new example-app --gitlab="--public" --organization="laravel"`

**Comment by driesvints** [comment]
We have no plans for this, sorry.

**Comment by driesvints** [comment]
We might accept a PR
