### ISSUE TITLE
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead

### ISSUE THREAD

**Issue by shaedrich** [laravel/installer#215]
- Installer Version: #.#.# (latest)

### Description:
> Package [`swiftmailer/swiftmailer`](https://github.com/swiftmailer/swiftmailer) is [abandoned](https://symfony.com/blog/the-end-of-swiftmailer), you should avoid using it. Use [`symfony/mailer`](https://github.com/symfony/mailer) instead.

### Steps To Reproduce:
Run `composer create-project laravel/laravel project-name` or-if you have already done that-`composer update`

**Comment by driesvints** [comment]
Pleas search the laravel/framework issue tracker before posting. We don't maintain swift mailer so there's nothing we can do here. Laravel 9 will switch to the new Symfony Mailer component.
