### ISSUE TITLE
API bootstrapping flag

### ISSUE THREAD

**Issue by fetzi** [laravel/installer#216]
As @taylorotwell mentioned on Twitter he started to work on an `--api` flag that strips down a new Laravel instance for API needs only.

Since there was no update since November I wanted to ask if it would be possible to put the PR out to the public and if we can support on finishing this feature.

It is already badly needed. 😉

**Comment by driesvints** [comment]
It's still being worked on. We'll communicate when we're closer to a release 👍

**Comment by fetzi** [comment]
@driesvints can you tell us an ETA for this?

**Comment by driesvints** [comment]
No sorry
