### ISSUE TITLE
Cannot install latest Laravel 9.0 when my /usr/bin/php points to php7.4

### ISSUE THREAD

**Issue by codemonkey76** [laravel/installer#220]
- Installer Version: 4.2.10

### Description:
I have the alias setup so that i run the installer with the correct PHP version:
alias laravel="/usr/bin/php8.1 ~/.config/composer/vendor/bin/laravel"

when I run "laravel new test", I get laravel/framework version 8.6.11
But 
if i set default php version using
"sudo update-alternatives --set php /usr/bin/php8.1" and then run "laravel new test", i get the laravel 9.0 framwork

### Steps To Reproduce:
1. install php 7.4 alongside php 8.1
2. Set php7.4 as default (update-alternatives --set php /usr/bin/php7.4)
3.  Run laravel installer with php8.1 (/usr/bin/php8.1 ~/.config/composer/vendor/bin/laravel new test)
4. Project will be created uising the old framework (8.6.11)

### Expected results:
1. Laravel/framework 9.0 should be used.

**Comment by driesvints** [comment]
If I do: `/opt/homebrew/Cellar/php/8.1.1/bin/php /Users/driesvints/.composer/vendor/bin/laravel new test-lara9`

It installs Laravel 9 for me. PHP 7.4 is installed as well. So I don't think there's an issue here and something specific to your local install is happening. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by codemonkey76** [comment]
> If I do: `/opt/homebrew/Cellar/php/8.1.1/bin/php /Users/driesvints/.composer/vendor/bin/laravel new test-lara9`
> 
> It installs Laravel 9 for me. PHP 7.4 is installed as well. So I don't think there's an issue here and something specific to your local install is happening. Please try a support channel:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Did you have php 7.4 as your default?

i.e. if you do php -v do you get 7.4 or 8.1?

This issue seems to only occur if the default php on the system is 7.4

**Comment by kw-pr** [comment]
With Linux/Ubuntu this did not worked for me:

`php8.1 ~/.composer/vendor/bin/laravel new test-lara9`

To make it work, I switched php version with this:

`sudo update-alternatives --set php /usr/bin/php8.1`

**Comment by ahmedmaazin** [comment]
> > If I do: `/opt/homebrew/Cellar/php/8.1.1/bin/php /Users/driesvints/.composer/vendor/bin/laravel new test-lara9`
> > It installs Laravel 9 for me. PHP 7.4 is installed as well. So I don't think there's an issue here and something specific to your local install is happening. Please try a support channel:
> > 
> > * [Laracasts Forums](https://laracasts.com/discuss)
> > * [Laravel.io Forums](https://laravel.io/forum)
> > * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> > * [Discord](https://discordapp.com/invite/KxwQuKb)
> > * [Larachat](https://larachat.co)
> > * [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
> 
> Did you have php 7.4 as your default?
> 
> i.e. if you do php -v do you get 7.4 or 8.1?
> 
> This issue seems to only occur if the default php on the system is 7.4

I can confirm this is in-fact true! Happened to me as well as I had `php@7.4` as my default php. Had to change to `php@8.0` to get the latest Laravel version 9 installed via `laravel new app`.

If I am not mistaken, I guess this is not an issue though as Laravel 9 requires PHP >= 8.0 at least.
