### ISSUE TITLE
unknown flag: --source

### ISSUE THREAD

**Issue by petericebear** [laravel/installer#221]
- Installer Version: 4.2.10

### Description:
- Using PHP 8.1.3
- Git version 2.35.1

### Steps To Reproduce:
laravel new projectname --github --branch="main" --jet --stack livewire

After installing Laravel and it's dependencies the error comes with:

```bash
unknown flag: --source
Usage:  gh repo create [<name>] [flags]
```

**Comment by petericebear** [comment]
For people getting the same error: 

```bash
brew upgrade gh
```

**Comment by driesvints** [comment]
Was just about to ask if you were on the latest `gh` CLI 😅

**Comment by petericebear** [comment]
Yeah, fun stuff :) I totally over read the GH thing.
