### ISSUE TITLE
Add git support to Laravel Sail initialization (laravel.build)

### ISSUE THREAD

**Issue by Danysan1** [laravel/installer#224]
Premise: [laravel/sail-server](https://github.com/laravel/sail-server) would probably have been a more appropriate repository for this feature request, but issues are not enabled there and this is the most closely related repository.

In #185 it has been added support for git bootstrapping, but currently it can't be used when initializing a Sail app through https://laravel.build as documented in https://laravel.com/docs/9.x/installation#your-first-laravel-project .
For example, calling https://laravel.build/example-app you get the command `laravel new example-app`.

It would be nice if it was possible to ask for git bootstrapping. For example adding the `git` parameter ( https://laravel.build/example-app?git or https://laravel.build/example-app?with=mysql&git ) you should be able to obtain `laravel new example-app --git` (in a similar fashion to the parameter `devcontainer` which when added enables the devcontainer functionality.

**Comment by driesvints** [comment]
Yes I think this could be cool. Depending on the amount of code that's added to the install script it could be done. You can try a PR if you like. Thanks!
