### ISSUE TITLE
roave/security-advisories flags default project name

### ISSUE THREAD

**Issue by KenLewis** [laravel/installer#226]
- Installer Version: 4.2.10

### Description:
On April 12th, 2022, `laravel/laravel` was added to `roave/security-advisories` to block versions <5.8.38. Since all new projects start with the `name` in the composer.json set as `laravel/laravel` this will cause subsequent composer updates to fail with the following message:

```
  Problem 1
    - laravel/laravel is present at version 1.0.0+no-version-set and cannot be modified by Composer
    - roave/security-advisories dev-latest conflicts with laravel/laravel <=5.8.38.
    - Root composer.json requires roave/security-advisories dev-latest -> satisfiable by roave/security-advisories[dev-latest].
```

I know that users should change the name of the project in composer.json, but it's never been an issue before and can be confusing to people who never had a reason to change it before.

I recommend setting the `name` in composer.json to the project name specified in the command.

### Steps To Reproduce:
- Install Laravel with the installer 
- add `roave/security-advisories` (`composer require --dev roave/security-advisories:dev-latest`)
- run `composer update`

Link to `roave/secutity-advisories` update: https://github.com/Roave/SecurityAdvisories/commit/21d0504612c544af1d8ce000e5e0301aa8bbde7c

**Comment by driesvints** [comment]
Not sure we'll take any action here for one package, sorry.
