### ISSUE TITLE
Set version to install

### ISSUE THREAD

**Issue by perepaul** [laravel/installer#229]
The laravel install is very robust as it helps with many thing that would be done manually, ie. setting up a github repo, initialising git and lots more. I have been receiving requests from employers to run laravel 8 or versions below 8, please can you add a flag were we can set the version of laravel we'd want to install?

laravel new example-app --version ^8.0

it will be really helpful for legacy support.

**Comment by driesvints** [comment]
We have no plans to allow people to install older Laravel versions. Please only start new projects with the latest Laravel version.

**Comment by srmklive** [comment]
@driesvints are there still plans to add support for this. I actually have a PR ready for this.

**Comment by driesvints** [comment]
No sorry. Only latest Laravel is supported and we’ll probably never change that. We don’t want to recommend installing older versions.
