### ISSUE TITLE
Fatal error: default value for parameters with a class type hint can only be NULL

### ISSUE THREAD

**Issue by fmp777** [laravel/installer#243]
- Installer Version: 4.2.16

### Description:
Trying to install within a user on a server with multiple php versions. Cannot change the global default of the server to php8.1 so I have installed my own composer.phar and setup an alias to run php8.1 ~/.bin/composer.phar then I did the same for laravel installer: alias laravel='php8.1 ~/.config/composer/vendor/bin/laravel'

This got the laravel cli running fine with laravel -v showing the version.

However, when I try to run `laravel new my-project` it has the fatal error - but what baffles me is why its in a global system file: `/usr/share/php/Symfony/Component/Console/Application.php`

I am sure whatever that file is is an older version, but why would my local laravel bin be using /usr/share/php ?  Is there any way I can change that?

### Steps To Reproduce:
Not really reproducible, as you have to have the unique environment setup I have.

**Comment by driesvints** [comment]
The installer isn't really meant to be used on a server but rather on your own machine to start a new project. I don't think we'll be taking any action here now, sorry.
