### ISSUE TITLE
install laravel globaly not working

### ISSUE THREAD

**Issue by wahyuadjiep** [laravel/installer#246]
I have a problem                                                                                                         
  with curl error 56 while downloading https://repo.packagist.org/p2/laravel/installer~dev.json: Received H  
  TTP code 503 from proxy after CONNECT   

please help me

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
