### ISSUE TITLE
Define version in new project

### ISSUE THREAD

**Issue by kromodoro** [laravel/installer#250]
I'm starting in Laravel this week, and I noticed that there are 3 ways to create a new project.

But only via composer I can define the framework version.

Via CURL or Laravel installer I don't have any way to set the version I want to start a new project.

![image](https://user-images.githubusercontent.com/21073299/211618210-036b1b9d-91b6-4260-a9a3-aa19e1993cc0.png)
> Laravel Installer 4.2.17

**Comment by driesvints** [comment]
You always get the latest version which should be the default for every new project 👍
