### ISSUE TITLE
Not able to install laravel via composer

### ISSUE THREAD

**Issue by suhasiniravichandran** [laravel/installer#265]
### Installer Version

composer version - 2.5.8, PHP version - 7.4, centOS version - 7.9

### Description

[root@localhost ~]# **composer global require laravel/installer**

Changed current directory to /root/.config/composer
./composer.json has been updated
Running composer update laravel/installer
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 13 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-php80 (v1.27.0): Extracting archive
  - Installing symfony/process (v5.4.24): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.27.0): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.27.0): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.27.0): Extracting archive
  - Installing symfony/polyfill-ctype (v1.27.0): Extracting archive
  - Installing symfony/string (v5.4.22): Extracting archive
  - Installing symfony/deprecation-contracts (v2.5.2): Extracting archive
  - Installing psr/container (1.1.2): Extracting archive
  - Installing symfony/service-contracts (v2.5.2): Extracting archive
  - Installing symfony/polyfill-php73 (v1.27.0): Extracting archive
  - Installing symfony/console (v5.4.24): Extracting archive
  - Installing laravel/installer (v4.5.0): Extracting archive
 0/3 [>---------------------------]   0%    Skipped installation of bin bin/laravel for package laravel/installer: file not found in package
Generating autoload files

In ClassMapGenerator.php line 129:
                                                                                                                                           
  Could not scan for classes inside "/root/.config/composer/vendor/symfony/polyfill-php73/Resources/stubs" which does not appear to be a   
  file nor a folder    

**This is my composer.json** 

  GNU nano 2.3.1                                 File: composer.json                                                                        

{
    "require": {
        "laravel/installer": "*"
    }
}

**This is my generated composer.lock**

{
    "_readme": [
        "This file locks the dependencies of your project to a known state",
        "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies",
        "This file is @generated automatically"
    ],
    "content-hash": "07880592eb9083f50c88030aef76c6df",
    "packages": [
        {
            "name": "laravel/installer",
            "version": "v4.5.0",
            "source": {
                "type": "git",
                "url": "https://github.com/laravel/installer.git",
                "reference": "e3d3b3d73833662429dd0812e481a6fa39e8758f"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/laravel/installer/zipball/e3d3b3d73833662429dd0812e481a6fa39e8758f",
                "reference": "e3d3b3d73833662429dd0812e481a6fa39e8758f",
                "shasum": ""
            },
            "require": {
                "php": "^7.3|^8.0",
                "symfony/console": "^4.0|^5.0|^6.0",
                "symfony/process": "^4.2|^5.0|^6.0"
            },
            "require-dev": {
                "phpstan/phpstan": "^1.10",
                "phpunit/phpunit": "^8.0|^9.3"
            },
            "bin": [
                "bin/laravel"
            ],
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "3.x-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Laravel\\Installer\\Console\\": "src/"
                }

                                                                                                                    
                                    

### Steps To Reproduce

$ composer global require laravel/installer

**Comment by osbre** [comment]
@suhasiniravichandran Not sure but can it be related to the fact that `composer` is being executed as root?

And I don't think reproducible steps would work as the package simply installs fine on other machines

**Comment by driesvints** [comment]
I can install the installer fine on 7.4:

<img width="1032" alt="Screenshot 2023-07-03 at 11 11 58" src="https://github.com/laravel/installer/assets/594614/475e5db2-dc7c-4bfe-9397-070548398e80">

Tbh, it's not ideal anymore to use 7.4 because you can't install Laravel v10 on it. We should probably bump the installer to the latest PHP version.

**Comment by suhasiniravichandran** [comment]
I updated my PHP version from 7.4 to 8.1, still I can't install Laravel

***@***.*** ]# composer global require laravel/installer
Changed current directory to /root/.config/composer
./composer.json has been updated
Running composer update laravel/installer
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 13 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-php80 (v1.27.0): Extracting archive
  - Installing symfony/process (v5.4.24): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.27.0): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.27.0): Extracting
archive
  - Installing symfony/polyfill-intl-grapheme (v1.27.0): Extracting archive
  - Installing symfony/polyfill-ctype (v1.27.0): Extracting archive
  - Installing symfony/string (v5.4.22): Extracting archive
  - Installing symfony/deprecation-contracts (v2.5.2): Extracting archive
  - Installing psr/container (1.1.2): Extracting archive
  - Installing symfony/service-contracts (v2.5.2): Extracting archive
  - Installing symfony/polyfill-php73 (v1.27.0): Extracting archive
  - Installing symfony/console (v5.4.24): Extracting archive
  - Installing laravel/installer (v4.5.0): Extracting archive
 0/3 [>---------------------------]   0%    Skipped installation of bin
bin/laravel for package laravel/installer: file not found in package
Generating autoload files

In ClassMapGenerator.php line 129:


  Could not scan for classes inside
"/root/.config/composer/vendor/symfony/polyfill-php73/Resources/stubs"
which does not appear to be a
  file nor a folder

**Comment by lechuhuuha** [comment]
try 

```bash
rm -rf vendor/
```
then

```bash
composer install
```
