### ISSUE TITLE
Cannot Install Pest on some shells

### ISSUE THREAD

**Issue by rajabilal555** [laravel/installer#272]
### Installer Version

5.0.2

### Description

When selecting no Starter Kit on the initial prompt, pest fails to installs on Windows Powershell.
Investigating this led me to the composer docs on the caret symbol where I discovered that it has to be escaped on Windows powershell.

![Screenshot 2023-08-15 223235](https://github.com/laravel/installer/assets/15360941/783b9414-b08e-4a53-99a5-902e3f5b1cb2)
https://getcomposer.org/doc/articles/versions.md#caret-version

# Error:
![image](https://github.com/laravel/installer/assets/15360941/2a6d047d-3486-4fa8-8b1f-901c0faa826f)

### Steps To Reproduce

Step 1: On `"Would you like to install a starter kit?"` Select none for No starter kit.

Step 2: On `"Which testing framework do you prefer?"` Enter 1 for PEST

![image](https://github.com/laravel/installer/assets/15360941/bb54bc3b-0709-45cf-9189-417b8de33810)

**Comment by crynobone** [comment]
Can you test using the following:

```bash
composer require --dev "pestphp/pest:^2.0" "pestphp/pest-plugin-laravel:^2.0"
```

**Comment by rajabilal555** [comment]
> Can you test using the following:
> 
> ```shell
> composer require --dev "pestphp/pest:^2.0" "pestphp/pest-plugin-laravel:^2.0"
> ```
@crynobone That also does not work

![image](https://github.com/laravel/installer/assets/15360941/becb5ec9-0ddb-4f1c-a4c8-4d51b42c69be)

**Comment by rajabilal555** [comment]
Since the other starter kit options do install pest correctly, I checked the [breeze installer](https://github.com/laravel/breeze/blob/a1358dc8a4d0d120a1aaa1160ff2b7cf62cd9f48/src/Console/InstallCommand.php#L81) and they are using the [`Process`](https://github.com/symfony/symfony/blob/08018d8d71d2cf46af58e53d322bdf6fe7e3b482/src/Symfony/Component/Process/Process.php#L143C21-L143C32) constructor which handles escape characters instead of the `fromShellCommandline` that is used by this repo.

**Comment by driesvints** [comment]
We have a PR up so let's continue the discussion there. Thanks!
