### ISSUE TITLE
"globally installing the Laravel installer via Composer" $PATH issue? 

### ISSUE THREAD

**Issue by gdonald** [laravel/installer#276]
### Installer Version

^5.0

### Description

The command to "globally installing the Laravel installer via Composer" does not seem to work for me.  I am using the instructions found on https://laravel.com/docs/10.x#your-first-laravel-project:

`> composer global require laravel/installer`

Changed current directory to /Users/gd/.composer
./composer.json has been updated
Running composer update laravel/installer
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Writing lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
9 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found
Using version ^5.0 for laravel/installer

`> laravel new example-app`

zsh: command not found: laravel

If I perform `find . -type f -name laravel` I see there are two files:

./.composer/vendor/bin/laravel
./.composer/vendor/laravel/installer/bin/laravel 

Is it expected that I augment my `$PATH` to add one or both of these directories?  There doesn't seem to be any mention of doing this on https://laravel.com/docs/10.x#your-first-laravel-project so I am unsure if this is the problem or if the initial command failed to work properly.

### Steps To Reproduce

Run the commands found on https://laravel.com/docs/10.x#your-first-laravel-project:

`> composer global require laravel/installer`

`> laravel new example-app`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by gdonald** [comment]
What a silly policy.

**Comment by JeeMo** [comment]
For those of you who find this:
You probably just need to export `./.composer/vendor/bin/laravel` to your path

**Comment by simushkin-brights** [comment]
19.10.2025 - the issue still exists

**Comment by stancl** [comment]
This isn't an issue with the Laravel installer. When you use `composer global ...`, **you** should have `~/.composer/vendor/bin/` in `$PATH`. Whether it's added automatically on your system is likely a matter of how you went about installing composer.
