### ISSUE TITLE
Option --branch isn't working

### ISSUE THREAD

**Issue by torvicv** [laravel/installer#282]
### Installer Version

5.1.1

### Description

Hello, I am trying install laravel 9 version.

I have tried:  laravel new l9 --git --branch="9.5.2"  and laravel new l9 --git --branch="9.x".

But I just got  to install laravel 10.

I am working on ubuntu 22.04.

Thank you.

### Steps To Reproduce

to install latest latest laravel installer.

run: laravel new l9 --git --branch="9.5.2"  | laravel new l9 --git --branch="9.x"

**Comment by crynobone** [comment]
https://github.com/laravel/installer/blob/7d97ef155e395079ab586ffcb2dbbdae27be2e05/src/NewCommand.php#L46 

The option description suggest that the will register the project git to use `9.5.2` as the default branch instead of `main`.

**Comment by crynobone** [comment]
We no longer supporting Laravel 9 and I don't believe the installer support Laravel 9 installation.

**Comment by torvicv** [comment]
Thank you for your reply.
