### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by sixtusagbo** [laravel/installer#286]
### Installer Version

5.1.2

### Description

The installation is not even starting at all. I'm getting this error:

```
In Interactivity.php line 32:

  Required.
```

### Steps To Reproduce

`composer global require laravel/installer`

`laravel new namodin`

**Comment by jessarcher** [comment]
Hey @sixtusagbo,

What operating system are you running the `laravel new` command on?

**Comment by sixtusagbo** [comment]
Windows 10 Version 22H2 (OS Build 19045.3448)

**Comment by jessarcher** [comment]
Thanks @sixtusagbo,

Are you able to give me the results of this command:

```
php -r "var_dump(stream_isatty(STDIN));"
```

(I'm not sure if it should be `php.exe` instead of just `php`)

**Comment by sixtusagbo** [comment]
The result of that command is `bool(true)`

**Comment by iyefreedy** [comment]
I've had the same issue as @sixtusagbo mentioned.
Is it solved ?

**Comment by jessarcher** [comment]
Hi @iyefreedy,

Not yet. Could you please tell me your operating system and the result of running the command from https://github.com/laravel/installer/issues/286#issuecomment-1740147145.

**Comment by iyefreedy** [comment]
![image](https://github.com/laravel/installer/assets/58893112/04594769-55e2-4065-ab9b-c50d9569911f)
This is the result of the command.
And I am using Windows 10 Education 64-bit operating system (10.0, Build 190454)

**Comment by jessarcher** [comment]
Thanks both!

I'm struggling to figure out what's going on here. The code that triggers that error should only execute if `stream_isatty(STDIN)` is `false`.

I'm just setting up a Windows machine to try to replicate this.

**Comment by jessarcher** [comment]
@iyefreedy are you also using mingw on bash? Or something different?

**Comment by jessarcher** [comment]
I've replicated the issue.

Very strange behaviour. The `stream_isatty` function returns differently depending on whether you execute the script directly, or pass it as an argument to `php.exe`. 

Take the following `test.php` file for example:

```php
#!/usr/bin/env PHP
<?php

var_dump(stream_isatty(STDIN));
```

And note the different result depending on how you execute it:

```sh
$ php test.php
bool(true)

$ ./test.php
bool(false)
```

While I look into this, you can run the installer with the `-n` flag to make it non-interactive. E.g.:

```sh
laravel new example-app -n
```

**Comment by jessarcher** [comment]
This is caused by mintty and its use of a pipe instead of a TTY.

`php` is aliased to `wintty php.exe`, which is why that works. `php.exe` is not aliased, nor are scripts with a shebang, so those don't work.

I can't find a reliable way to detect whether `STDIN` is interactive when using mintty so I need to re-think the approach for non-interactive mode in https://github.com/laravel/prompts.

The easiest solution for the time being is to probably just make the fallback mode take priority over the non-interactive mode.

**Comment by driesvints** [comment]
Try again all?

**Comment by jessarcher** [comment]
LGTM (after `composer global update`)

![image](https://github.com/laravel/installer/assets/4977161/183654c7-c7b2-44b9-9bd5-c6113d3432ad)

**Comment by mstfkhazaal** [comment]
I have same error in Mac
i use sail https://laravel.com/docs/10.x/installation#sail-on-macos
