### ISSUE TITLE
Docs link broken/missing from docs

### ISSUE THREAD

**Issue by caseydwyer** [laravel/installer#296]
### Installer Version

5.x

### Description

Hi team,

Sorry for the smallness of this issue, but wasn't sure where to raise the question. On the `10.x` docs, there's no mention of the installer. It looks like the last time it was referenced was in `9.x`. This repo's readme has a link to the `#installing-laravel` anchor, but that header doesn't exist on the linked docs page. A search for "installer" comes up empty, too.

Wasn't sure if this was intentional, a sign of planned sunsetting for the installer, or something else.

Thanks in advance for any clarity you can provide, and for all your work on the framework! ♥

### Steps To Reproduce

See `readme` for [link](https://laravel.com/docs/10.x#installing-laravel).

**Comment by driesvints** [comment]
Thanks @caseydwyer. Investigating this.

**Comment by iRaziul** [comment]
> Thanks @caseydwyer. Investigating this.

![image](https://github.com/laravel/installer/assets/51883557/5e352e03-8dbc-4d6a-94f9-603673935d57)
This section is missing on the Laravel 10 docs
