### ISSUE TITLE
Error installing Laravel on a Github Codespace (it worked yesterday 2023-12-18)

### ISSUE THREAD

**Issue by Foundasys** [laravel/installer#297]
### Installer Version

Unknown

### Description

This command does not work on a Github Codespace anymore:

curl -s "https://laravel.build/example-app?with=mysql,redis" | bash

It throws the following error:

latest: Pulling from laravelsail/php83-composer
Digest: sha256:bf8d87c943cacab0e04ead85e8c1db440e345fd1456714f736786ef4d18ba7b7
Status: Image is up to date for laravelsail/php83-composer:latest

   _                               _
  | |                             | |
  | |     __ _ _ __ __ ___   _____| |
  | |    / _` | '__/ _` \ \ / / _ \ |
  | |___| (_| | | | (_| |\ V /  __/ |
  |______\__,_|_|  \__,_| \_/ \___|_|

In Interactivity.php line 32:
             
  Required.  
             

new [--dev] [--git] [--branch BRANCH] [--github [GITHUB]] [--organization ORGANIZATION] [--stack [STACK]] [--breeze] [--jet] [--dark] [--typescript] [--ssr] [--api] [--teams] [--verification] [--pest] [--phpunit] [--prompt-breeze] [--prompt-jetstream] [-f|--force] [--] <name>

bash: line 17: cd: example-app: No such file or directory
bash: line 23: ./vendor/bin/sail: No such file or directory
bash: line 24: ./vendor/bin/sail: No such file or directory

Get started with: cd example-app && ./vendor/bin/sail up

### Steps To Reproduce

Create a Github Codespace and run : curl -s "https://laravel.build/example-app?with=mysql,redis" | bash

**Comment by Foundasys** [comment]
Also found this comment

https://github.com/laravel/installer/issues/286#issuecomment-1864819007

**Comment by phh** [comment]
@Foundasys I updated the sail-server with PHP 8.3 default today. Seems like that for some reason messed up the installment.

You can include `?php=82` to the url to fix this for now.

**Comment by kjaonline** [comment]
Adding `?php=82` worked for me for now.

Thanks!

**Comment by crynobone** [comment]
Should be solved via https://github.com/laravel/sail-server/pull/21
