### ISSUE TITLE
Call to `http://cabinet.laravel.com/*.zip` is returning a 404

### ISSUE THREAD

**Issue by gcarreno** [laravel/installer#303]
### Installer Version

2.3.0

### Description

It appears that the service at `cabinet.laravel.com` is missing the necessary archives that serve the install tool since the install tool is reporting 404 errors.

### Steps To Reproduce

After instructions on the [installation page](https://laravel.com/docs/10.x/installation), that tells us to:
```console
$ composer global require laravel/installer
```

When attempting:
- `laravel new test`
- `laravel new test --dev`

the response is:
```
In RequestException.php line 113:
                                                                                                             
  Client error: `GET http://cabinet.laravel.com/latest[-develop].zip` resulted in a `404 Not Found` response:.....
```

**Comment by driesvints** [comment]
Please update to the latest release.

**Comment by gcarreno** [comment]
Hey Dries(@driesvints),

This is not a very wise solution!! This is just a "_shoo, go away, don't bother me, I have better things to do_" kinda answer.

And why do I say that? Simples: I was following the current 10.x `Laravel` documentation.
If you follow the most updated and currently provided documentation, you should have some trust that it's gonna work.

So... you either update the package on `packagist.org` with a new release, or someone has to amend the current `Laravel` documentation to remove the `Laravel` installer option.

Wouldn't you agree?

Cheers,
Gus

**Comment by driesvints** [comment]
Hey Gus. We don’t maintain 2.x anymore. Please upgrade to 5.x and see if that version works. As per our support policy we only support the latest major releases of our packages.

**Comment by gcarreno** [comment]
Hey Dries(@driesvints),

Would never imply that you maintain stuff that is that old. If it did come across like that, I offer my deepest apologies!!

What I did want to stress out, is that your 10.x docs, the most recent ones I believe, is telling prospect users to do:
```console
$ composer global require laravel/installer
```
which I **did** and got version 2.3.0 from `packagist`!!

Someone should fix that with a new version being released so `packagist` delivers 5.x and not 2.3.0. That's the only thing I want to stress out!!

Again, I was just a naive user following the latest docs, and I got in trouble...

Hope this clarifies the entire dilema :smile: :people_hugging: !!

Cheers,
Gus

**Comment by jessarcher** [comment]
Hey @gcarreno, can you tell me what version of PHP you have? (`php -v`)

**Comment by gcarreno** [comment]
Hey Jess(@jessarcher):

My specs:
```console
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 23.10"
NAME="Ubuntu"
VERSION_ID="23.10"
VERSION="23.10 (Mantic Minotaur)"
VERSION_CODENAME=mantic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=mantic
LOGO=ubuntu-logo

$ php -v
PHP 8.2.10-2ubuntu1 (cli) (built: Sep  5 2023 14:37:47) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.10, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.10-2ubuntu1, Copyright (c), by Zend Technologies

$ composer --version
Composer version 2.6.6 2023-12-08 18:32:26
```

Hope this helps !!

Cheers,
Gus

**Comment by jessarcher** [comment]
Thanks, Gus.

All looks good - I'd have expected you to get the latest version of the installer. I can't see any obvious dependencies in versions greater than 2.3.0 that you wouldn't have.

Can you please try running `composer global require laravel/installer:^5.3` and see if Composer gives you any error messages that might point to the culprit?

**Comment by gcarreno** [comment]
Hey Jess(@jessarcher),

At first glance, I was gonna say that no problems would arise from that.

Alas, I was in error:
```console
$ composer global require laravel/installer:^5.3
Changed current directory to /home/gcarreno/.config/composer
./composer.json has been updated
Running composer update laravel/installer
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel/installer ^5.3 -> satisfiable by laravel/installer[v5.3.0].
    - laravel/installer v5.3.0 requires symfony/console ^6.2|^7.0 -> found symfony/console[v6.2.0, ..., v6.4.2, v7.0.0, v7.0.1, v7.0.2] but the package is fixed to v4.4.49 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

Nonetheless, and following the provided hint to add `-W`, now all is well!!
Also checked if anything else on my `global` was broken, but all is good there as well!!

But, still, and I apologise for keep mentioning this, that is not what the current 10.x docs mentions one to do!!

I'm still waiting for the update being reflected on `packagist`. This is no one wants to edit the current 10.x docs!!

@jessarcher: Many thanks for your, most precious, time in helping us come to a fruitful conclusion!!

Cheers,
Gus

**Comment by jessarcher** [comment]
I'm glad that solved it, Gus! I'll chat with Dries about potential documentation improvements. Not sure what we can do about Packagist short of removing the old versions so composer errors out instead of installing something that no longer works.

**Comment by driesvints** [comment]
> which I did and got version 2.3.0 from packagist!!

ooh I didn't get that indeed. Thanks for clarifying. We'll improve the docs about this for sure.

**Comment by gcarreno** [comment]
Hey Dries(@driesvints) and Jess(@jessarcher),

This is rather quite odd and I'm unable to explain it!!

Since I'm banging about `packagist` and `composer` and all that, I went to `packagist` to confirm what was the latest version.
To my utter surprise, `packagist` does **INDEED** list version `5.4.0` as the latest.

I'm now quite baffled as to why my system just installed `2.3.0` :shrug: 

I do apologise for the fact that I pulled you into this wild goose chase when the issue clearly resided on some fluke in my system!!!

My sincerest thanks to you both for coming along on this ride and providing your precious time to it!!! :people_hugging: 

Cheers,
Gus
