### ISSUE TITLE
issues when install laravel with mysql

### ISSUE THREAD

**Issue by webtinax** [laravel/installer#315]
### Installer Version

5.5.1

### Description

when install steps => select db mysql problem in .env and .env.example

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=((((([folder_insatall laravel show here :O]))))) => must be laravel
DB_USERNAME=root
DB_PASSWORD=

### Steps To Reproduce

laravel new xxxxx

when mysql :

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=xxxxx
DB_USERNAME=root
DB_PASSWORD=

**Comment by crynobone** [comment]
Just tested with v5.5.1 

```bash
laravel new sandbox
```

#### `.env`

```ini
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=sandbox
DB_USERNAME=root
DB_PASSWORD=
```

#### `.env.example`

```ini
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=sandbox
DB_USERNAME=root
DB_PASSWORD=
```

I don't see any issue here as everything is working as expected.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
