### ISSUE TITLE
[11.x] The config files are back in the skeleton

### ISSUE THREAD

**Issue by codebarista** [laravel/installer#316]
### Installer Version

5.5.2 

### Description

Hi, I'm really looking forward to the new version of Laravel and this isn't necessarily a bug, but in a new dev installation the config files are back in the skeleton. Is that intentional since [they were specifically removed](https://github.com/laravel/laravel/pull/6188)?

### Steps To Reproduce

`laravel new eleven --dev`
...
_Publish configs: No_
...
`ls -la eleven/config`

**Comment by driesvints** [comment]
It is: https://twitter.com/taylorotwell/status/1761128243732619330

**Comment by codebarista** [comment]
Oh, thanks and sorry 👍
