### ISSUE TITLE
Database name is set to directory even with an actual DBMS set in options

### ISSUE THREAD

**Issue by artshade** [laravel/installer#328]
### Installer Version

5.7.0

### Description

Dear Developers,

Thank you for the awesome project!

For some reason, even with option `--database mariadb` set, "dotenv" files get replaced with environment variable `DB_DATABASE` with the directory path possibly on the following lines: [./src/NewCommand.php#L300-L310](https://github.com/laravel/installer/blob/master/src/NewCommand.php#L300-L310).

I see that the installer expects "name" of project and not "directory name" as Composer for the positional argument, but... contents of `./.env` may become:

```env
DB_CONNECTION=mariadb
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=./project
DB_USERNAME=root
DB_PASSWORD=
```

More to that, is it possible to somehow pre-configure database options prior the execution? Currently, I don't see any way to set definite database configuration prior migrations when creating a new project not for SQLite but some actual database server.

In the result, even with `laravel new --database mariadb --jet ... -- project;`, we have:

<img width="603" alt="image" src="https://github.com/laravel/installer/assets/25136754/3e30cb07-51f1-44cb-a049-0c33835be0d5">

Is it expected?

Best and kind regards

### Steps To Reproduce

Execute command:

```bash
laravel new \
    --no-interaction \
    --database mariadb \
    --jet \
        --stack inertia --git -- \
    './project';
```

**Comment by crynobone** [comment]
There's already closed PR that might be similar to this, see #326. Otherwise, you are free to attempt submitting a PR for us for us to review.
