### ISSUE TITLE
Database.sqlite is created even if you slect mysql

### ISSUE THREAD

**Issue by rabol** [laravel/installer#329]
### Installer Version

5.7.0

### Description

Even if MySql is selected as database, the database.sqlite is created

### Steps To Reproduce

laravel new xxx
then in the section of database select MySQL, say no to migrate and look at the database directory and you will see that there is a database.sqlite

**Comment by crynobone** [comment]
This seems to be the expected behavior with `compsoer install` used during the installer + post create/install command. Feel free to attempt PR changes to the behavior.
