### ISSUE TITLE
Installer asks user password every time

### ISSUE THREAD

**Issue by askdkc** [laravel/installer#347]
### Installer Version

5.8.3

### Description

Installer now asks user password every time I run `laravel new myproject`.
Is there anyway I can avoid this?

### Steps To Reproduce

When I run `laravel new myproject`, the Laravel installer checks if the user is using Valet or Herd during the installation process. This check occurs in the following part of the code:

https://github.com/laravel/installer/blob/2ab2384ebb5e9cf0581f1fcbd092c3be8b920fe9/src/NewCommand.php#L866

On my macOS, this code executes the command `valet tld -v`, which prompts for the user password to run correctly. It's frustrating to input the password every time I create a new Laravel project. Is there any way to avoid or skip this password prompt?

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by askdkc** [comment]
@crynobone 

Turns out, I need to run `valet trust` in order to avoid this password issue.

**Comment by JangoCG** [comment]
> valet trust

Thank you I had the excat same issue

**Comment by askdkc** [comment]
@JangoCG 

I feel your pain.
