### ISSUE TITLE
Unnecessary SQLite Migrations Run at Installation

### ISSUE THREAD

**Issue by Usmanzahidcode** [laravel/installer#349]
During the setup of a new Laravel application, SQLite migrations are executed automatically, even before selecting a specific database driver. This may be redundant for users who do not intend to use SQLite.

The current behaviour initiates SQLite migrations prematurely, potentially causing unnecessary database operations and migrations.

Consider delaying SQLite migrations until a database driver is explicitly selected or configured during the setup process. This adjustment could improve the setup experience, especially for users focusing on alternative databases from the start.

**Comment by crynobone** [comment]
Can you share the output of `composer global show -D`

**Comment by Usmanzahidcode** [comment]
$ composer global show

Changed current directory to C:/Users/Nexgen/AppData/Roaming/Composer
doctrine/inflector               2.0.8    PHP Doctrine Inflector is a small library that can perform string manipulations w...
illuminate/collections           v10.32.1 The Illuminate Collections package.
illuminate/conditionable         v10.32.1 The Illuminate Conditionable package.
illuminate/contracts             v10.32.1 The Illuminate Contracts package.
illuminate/filesystem            v10.32.1 The Illuminate Filesystem package.
illuminate/macroable             v10.32.1 The Illuminate Macroable package.
illuminate/support               v10.32.1 The Illuminate Support package.
laravel/installer                v5.1.3   Laravel application installer.
laravel/prompts                  v0.1.13
nesbot/carbon                    2.71.0   An API extension for DateTime that supports 281 different languages.
psr/clock                        1.0.0    Common interface for reading the clock.
psr/container                    2.0.2    Common Container Interface (PHP FIG PSR-11)
psr/simple-cache                 3.0.0    Common interfaces for simple caching
symfony/console                  v6.3.8   Eases the creation of beautiful and testable command line interfaces
symfony/deprecation-contracts    v3.4.0   A generic function and convention to trigger deprecation notices
symfony/finder                   v6.3.5   Finds files and directories via an intuitive fluent interface
symfony/polyfill-ctype           v1.28.0  Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme   v1.28.0  Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-normalizer v1.28.0  Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring        v1.28.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php80           v1.28.0  Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                  v6.3.4   Executes commands in sub-processes
symfony/service-contracts        v3.4.0   Generic abstractions related to writing services
symfony/string                   v6.3.8   Provides an object-oriented API to strings and deals with bytes, UTF-8 code point...
symfony/translation              v6.3.7   Provides tools to internationalize your application
symfony/translation-contracts    v3.4.0   Generic abstractions related to translation
voku/portable-ascii              2.0.1    Portable ASCII library - performance optimized (ascii) string functions for php.

**Comment by crynobone** [comment]
Update `laravel/installer`: https://github.com/laravel/installer/releases/tag/v5.8.1
