### ISSUE TITLE
Root composer.json requires pestphp/pest-plugin-laravel ^3.0

### ISSUE THREAD

**Issue by blak1984** [laravel/installer#356]
### Installer Version

5.8.3

### Description

When installing a new project we get this error:

```console
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires pestphp/pest-plugin-laravel ^3.0 -> satisfiable by pestphp/pest-plugin-laravel[v3.0.0].
    - pestphp/pest-plugin-laravel v3.0.0 requires pestphp/pest ^3.0.0 -> found pestphp/pest[3.x-dev] but it does not match your minimum-stability.
```

### Steps To Reproduce

1. run `laravel new my-app`
2. choose all the default options
3. see the error in console which prevents you from being able to install any packages as well

**Comment by blak1984** [comment]
PR here: https://github.com/laravel/installer/pull/357

**Comment by crynobone** [comment]
Pest 3 was tagged 2 hours ago should solve this issue: https://github.com/pestphp/pest/releases/tag/v3.0.0
