### ISSUE TITLE
the laravel installer is bring this issue

### ISSUE THREAD

**Issue by NPKIN1998** [laravel/installer#358]
### Installer Version

5.8.5

### Description

i am getting this error on debian 12

### Steps To Reproduce

➜ cd text
PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /home/kintech/.config/composer/vendor/laravel/installer/src/NewCommand.php:813
Stack trace:
#0 /home/kintech/.config/composer/vendor/laravel/installer/src/NewCommand.php(813): in_array()
#1 /home/kintech/.config/composer/vendor/laravel/installer/src/NewCommand.php(246): Laravel\Installer\Console\NewCommand->isParked()
#2 /home/kintech/.config/composer/vendor/symfony/console/Command/Command.php(279): Laravel\Installer\Console\NewCommand->execute()
#3 /home/kintech/.config/composer/vendor/symfony/console/Application.php(1029): Symfony\Component\Console\Command\Command->run()
#4 /home/kintech/.config/composer/vendor/symfony/console/Application.php(316): Symfony\Component\Console\Application->doRunCommand()
#5 /home/kintech/.config/composer/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun()
#6 /home/kintech/.config/composer/vendor/laravel/installer/bin/laravel(13): Symfony\Component\Console\Application->run()
#7 /home/kintech/.config/composer/vendor/bin/laravel(119): include('...')
#8 {main}
  thrown in /home/kintech/.config/composer/vendor/laravel/installer/src/NewCommand.php on line 813

**Comment by crynobone** [comment]
Can you provide the output of `$output`:

https://github.com/laravel/installer/blob/56898ec7a62a8cf157d86c1df583b2569a63ad53/src/NewCommand.php#L811C26-L811C42

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
