### ISSUE TITLE
The Chinese network is very complicated. In many cases, the download progress is very slow when creating laravel.

### ISSUE THREAD

**Issue by StringKe** [laravel/installer#84]
https://github.com/laravel/installer/blob/e22bcc91956911bae352e5b2f0efc26ad9c717c8/src/NewCommand.php#L137

Maybe you can call the current composer image configuration to download laravel？

**Comment by driesvints** [comment]
Why would that be faster than this approach?

**Comment by StringKe** [comment]
中国因为很多人无法快速访问composer的镜像，会存在很多的代理composer镜像的网站
In China, because many people cannot quickly access the image of "composer", there will be many websites that represent "composer" images.

1. https://packagist.laravel-china.org
2. https://packagist.phpcomposer.com

**Comment by driesvints** [comment]
Would using the github archive be an option instead? https://github.com/laravel/laravel/archive/master.zip

**Comment by StringKe** [comment]
Of course you can use github archive, but no larave command is easy to use.

**Comment by driesvints** [comment]
@StringKe I meant: is using the Github url instead of the cabinet one an option for the Chinese network?

**Comment by StringKe** [comment]
yep，May be the proxy site of composer?

**Comment by driesvints** [comment]
> yep，May be the proxy site of composer?

what do you mean with proxy site of composer? Can you give a link to that? You said "yep" so is the github one an option or not?

**Comment by StringKe** [comment]
proxy site of composer

1. https://packagist.laravel-china.org  && https://learnku.com/laravel/composer
2. https://packagist.phpcomposer.com && https://pkg.phpcomposer.com/

Yes, github is also an option

**Comment by driesvints** [comment]
Heya, so the way the cabinet now works is that it pre-installs the skeleton for you so you only have to download a zip and are good to go. This is something custom we do which is hard to mimick in another way. So I'm afraid we're going to have to leave it as is for now. 

Feel free to fork the package and customize the installation in a way that you see fit!
